# Generated by Django 5.1.1 on 2024-09-18 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='authenticate',
        ),
    ]
